#!/usr/bin/env bash
# Upload file to server through ssh
PATH_TO_SSH_KEY=$4
PATH_TO_FILE=$1
USERNAME=$3
IP=$2
if [ "$#" -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME"@"$IP":~/
fi
