#!/usr/bin/env bash
# Show PID

echo $BASHPID > /var/run/holbertonscript.pid
trap 'echo "I hate the kill command"; rm /var/run/holbertonscript.pid; exit 0;' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm /var/run/holbertonscript.pid; exit 0;' SIGQUIT
while true; do
    trap 'echo "I am invincible!!!"' SIGTERM
    echo "To infinity and beyond"
    sleep 2
done
