#!/usr/bin/env bash
# Print numbers till 20

for ((x=1; x < 21; x++)); do
    echo "$x"
    case "$x" in
	4)
	    echo "bad luck from China" ;;
	9)
	    echo "bad luck from Japan" ;;
	17)
	    echo "bad luck from Italy" ;;
    esac
done
